import { atom } from 'jotai';

// Define the type for our branching logic
type BranchingType = 'main' | 'discuss' | 'debug';

interface BranchingState {
  sourceNodeId: string | null;
  type: BranchingType;
}

/**
 * @description Atom to track if this is the very first prompt in a new chat.
 * This determines the position of the main PromptBox.
 */
export const isInitialPromptAtom = atom<boolean>(true);

/**
 * @description Atom to hold the state for branching. It tracks which node 
 * to branch from and what type of branch to create.
 */
export const branchingStateAtom = atom<BranchingState>({
  sourceNodeId: null,
  type: 'main', 
});

/**
 * @description Atom to track the loading state. We'll store the ID of the 
 * node that is currently being generated by the AI to show a loading spinner.
 */
export const isLoadingAtom = atom<string | null>(null);
